---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis-test
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:^4.0
spec:
  releaseName: redis-test
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: redis
    version: 7.0.1
  values:
    image:
      repository: bitnami/redis
      tag: 4.0.14
