---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  releaseName: istio
  chart:
    repository: https://storage.googleapis.com/istio-release/
    name: istio
    version: 1.1.3
  values:
    global:
      mtls:
        enabled: false
      proxy:
        autoInject: disabled
    gateways:
      istio-ingressgateway:
        type: NodePort
      istio-egressgateway:
        enabled: true
    sidecarInjectorWebhook:
        enabled: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
