---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: 00-istio-init
  namespace: istio-system
spec:
  releaseName: 00-istio-init
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.1.3/charts/
    name: istio-init
    version: 1.1.3
