---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: 00-istio-init
  namespace: istio-system
spec:
  releaseName: 00-istio-init
  chart:
    git: ssh://git@git.blbl.cr/admin/gke.git
    ref: master
    path: charts/istio/1.1.3/istio-init
